import type { CharacterContentBundle } from '../../character-content/src/index.js';
import type { WorldContentBundle } from '../../world-content/src/index.js';

export const DEV_CHARACTER_CONTENT_BUNDLE = {
  bundleId: 'dev-content-bundle-0001',
  contentVersion: '0.0.1-dev',
  cueSchemaVersion: 'cue-v1',
  minClientCapability: '0.0.1-dev',
  characters: [
    {
      characterId: 'john-doe-01',
      contentVersion: '0.0.1-dev',
      displayName: 'John Doe 01',
      deityProxyLabel: 'placeholder',
      shortDescriptor: 'general structure placeholder',
      personalityTraits: ['placeholder'],
      flaws: ['placeholder'],
      values: ['placeholder'],
      speech: { register: 'placeholder', sentenceRhythm: 'placeholder', directness: 'medium', warmth: 'medium', profanity: 'none', forbiddenBehaviors: ['alter_saju_semantics'] },
      capabilities: [{ domain: 'general', role: 'primary', canInitiate: true, capabilityVersion: 'dev-v1' }],
      assetRefs: [],
      animationCueIds: [],
    },
    {
      characterId: 'john-doe-02',
      contentVersion: '0.0.1-dev',
      displayName: 'John Doe 02',
      deityProxyLabel: 'placeholder',
      shortDescriptor: 'career placeholder',
      personalityTraits: ['placeholder'],
      flaws: ['placeholder'],
      values: ['placeholder'],
      speech: { register: 'placeholder', sentenceRhythm: 'placeholder', directness: 'medium', warmth: 'medium', profanity: 'none', forbiddenBehaviors: ['alter_saju_semantics'] },
      capabilities: [{ domain: 'career', role: 'primary', canInitiate: true, capabilityVersion: 'dev-v1' }],
      assetRefs: [],
      animationCueIds: [],
    },
    {
      characterId: 'john-doe-03',
      contentVersion: '0.0.1-dev',
      displayName: 'John Doe 03',
      deityProxyLabel: 'placeholder',
      shortDescriptor: 'wealth placeholder',
      personalityTraits: ['placeholder'],
      flaws: ['placeholder'],
      values: ['placeholder'],
      speech: { register: 'placeholder', sentenceRhythm: 'placeholder', directness: 'medium', warmth: 'medium', profanity: 'none', forbiddenBehaviors: ['alter_saju_semantics'] },
      capabilities: [{ domain: 'wealth', role: 'primary', canInitiate: true, capabilityVersion: 'dev-v1' }],
      assetRefs: [],
      animationCueIds: [],
    },
    {
      characterId: 'john-doe-04',
      contentVersion: '0.0.1-dev',
      displayName: 'John Doe 04',
      deityProxyLabel: 'placeholder',
      shortDescriptor: 'relationship placeholder',
      personalityTraits: ['placeholder'],
      flaws: ['placeholder'],
      values: ['placeholder'],
      speech: { register: 'placeholder', sentenceRhythm: 'placeholder', directness: 'medium', warmth: 'medium', profanity: 'none', forbiddenBehaviors: ['alter_saju_semantics'] },
      capabilities: [{ domain: 'relationship', role: 'primary', canInitiate: true, capabilityVersion: 'dev-v1' }],
      assetRefs: [],
      animationCueIds: [],
    },
    {
      characterId: 'john-doe-05',
      contentVersion: '0.0.1-dev',
      displayName: 'John Doe 05',
      deityProxyLabel: 'placeholder',
      shortDescriptor: 'timing placeholder',
      personalityTraits: ['placeholder'],
      flaws: ['placeholder'],
      values: ['placeholder'],
      speech: { register: 'placeholder', sentenceRhythm: 'placeholder', directness: 'medium', warmth: 'medium', profanity: 'none', forbiddenBehaviors: ['alter_saju_semantics'] },
      capabilities: [{ domain: 'life_stage', role: 'primary', canInitiate: true, capabilityVersion: 'dev-v1' }],
      assetRefs: [],
      animationCueIds: [],
    },
  ],
} satisfies CharacterContentBundle;

export const DEV_WORLD_CONTENT_BUNDLE = {
  bundleId: DEV_CHARACTER_CONTENT_BUNDLE.bundleId,
  contentVersion: DEV_CHARACTER_CONTENT_BUNDLE.contentVersion,
  characterRelations: [
    { fromCharacterId: 'john-doe-01', toCharacterId: 'john-doe-02', relationType: 'placeholder_relation', summary: 'development-only placeholder relation' },
  ],
  episodes: [
    {
      episodeId: 'dev-first-contact',
      contentVersion: '0.0.1-dev',
      title: 'Placeholder Episode',
      synopsis: 'Development-only episode used to verify bundle validation and runtime projection.',
      participants: [
        { characterId: 'john-doe-01', role: 'lead' },
        { characterId: 'john-doe-02', role: 'support' },
      ],
      unlockRuleId: 'dev-first-contact-unlock',
    },
  ],
} satisfies WorldContentBundle;
