import {
  CHARACTER_FACT_AUTHORITY_REGISTRY_SCHEMA_VERSION_V1,
  type CharacterFactAuthorityRegistryV1,
} from './character-fact-authority-v1.js';

export const SEYEON_FACT_AUTHORITY_SOURCE_V1 = Object.freeze({
  path: 'docs/character/SEYEON_CHARACTER_BIBLE_DRAFT_V0_2.md',
  gitBlobSha: '2ecccbf4a1a7cb595b8a30f300f678d0a1e06999',
});

export const SEYEON_FACT_AUTHORITY_REGISTRY_V1 = Object.freeze({
  schemaVersion: CHARACTER_FACT_AUTHORITY_REGISTRY_SCHEMA_VERSION_V1,
  characterId: 'seyeon',
  sourceBible: SEYEON_FACT_AUTHORITY_SOURCE_V1,
  entries: Object.freeze([
    Object.freeze({
      factKey: 'identity.name',
      sourceAuthority: 'CANON',
      characterKnowledge: 'KNOWN',
      disclosureDefault: 'PUBLIC',
      sourceSection: 'B1',
      closureNote: '채택',
    }),
    Object.freeze({
      factKey: 'identity.exact_age',
      sourceAuthority: 'AUTHOR_UNDEFINED',
      characterKnowledge: 'NOT_APPLICABLE',
      disclosureDefault: 'NOT_APPLICABLE',
      sourceSection: 'B1',
      closureNote: 'Production 전 closure 필요',
    }),
    Object.freeze({
      factKey: 'identity.birthday',
      sourceAuthority: 'AUTHOR_UNDEFINED',
      characterKnowledge: 'NOT_APPLICABLE',
      disclosureDefault: 'NOT_APPLICABLE',
      sourceSection: null,
      closureNote: 'High-answerability gap',
    }),
    Object.freeze({
      factKey: 'identity.blood_type',
      sourceAuthority: 'AUTHOR_UNDEFINED',
      characterKnowledge: 'NOT_APPLICABLE',
      disclosureDefault: 'NOT_APPLICABLE',
      sourceSection: null,
      closureNote: '낮은 비용의 closure 후보',
    }),
    Object.freeze({
      factKey: 'identity.mbti_self_report',
      sourceAuthority: 'AUTHOR_UNDEFINED',
      characterKnowledge: 'NOT_APPLICABLE',
      disclosureDefault: 'NOT_APPLICABLE',
      sourceSection: null,
      closureNote: '성격 원인으로 사용하지 말고 self-report policy만 결정',
    }),
    Object.freeze({
      factKey: 'life.occupation_or_social_role',
      sourceAuthority: 'AUTHOR_UNDEFINED',
      characterKnowledge: 'NOT_APPLICABLE',
      disclosureDefault: 'NOT_APPLICABLE',
      sourceSection: 'B1',
      closureNote: 'Production 전 closure 필요',
    }),
    Object.freeze({
      factKey: 'life.current_living_base',
      sourceAuthority: 'AUTHOR_UNDEFINED',
      characterKnowledge: 'NOT_APPLICABLE',
      disclosureDefault: 'NOT_APPLICABLE',
      sourceSection: 'I5',
      closureNote: 'Production 전 closure 필요',
    }),
    Object.freeze({
      factKey: 'backstory.birth_or_growth_region',
      sourceAuthority: 'AUTHOR_UNDEFINED',
      characterKnowledge: 'NOT_APPLICABLE',
      disclosureDefault: 'NOT_APPLICABLE',
      sourceSection: 'J1',
      closureNote: '생활권 이동 가설은 HYPOTHESIS이며 authority 아님',
    }),
    Object.freeze({
      factKey: 'family.structure',
      sourceAuthority: 'AUTHOR_UNDEFINED',
      characterKnowledge: 'NOT_APPLICABLE',
      disclosureDefault: 'NOT_APPLICABLE',
      sourceSection: 'J2',
      closureNote: '가족 방향 가설은 HYPOTHESIS이며 authority 아님',
    }),
    Object.freeze({
      factKey: 'family.current_relationship',
      sourceAuthority: 'AUTHOR_UNDEFINED',
      characterKnowledge: 'NOT_APPLICABLE',
      disclosureDefault: 'NOT_APPLICABLE',
      sourceSection: 'J2',
      closureNote: 'Production 전 closure 필요',
    }),
    Object.freeze({
      factKey: 'backstory.major_turning_points',
      sourceAuthority: 'AUTHOR_UNDEFINED',
      characterKnowledge: 'NOT_APPLICABLE',
      disclosureDefault: 'NOT_APPLICABLE',
      sourceSection: 'J3',
      closureNote: '필요 최소 범위만 설계',
    }),
    Object.freeze({
      factKey: 'past_romance.existence',
      sourceAuthority: 'AUTHOR_UNDEFINED',
      characterKnowledge: 'NOT_APPLICABLE',
      disclosureDefault: 'NOT_APPLICABLE',
      sourceSection: 'J4',
      closureNote: '존재 여부부터 closure 필요',
    }),
    Object.freeze({
      factKey: 'social.important_non_user_relationships',
      sourceAuthority: 'AUTHOR_UNDEFINED',
      characterKnowledge: 'NOT_APPLICABLE',
      disclosureDefault: 'NOT_APPLICABLE',
      sourceSection: 'I3',
      closureNote: '일반적 사교성은 Canon이나 구체 관계는 미정',
    }),
    Object.freeze({
      factKey: 'life.current_responsibilities',
      sourceAuthority: 'AUTHOR_UNDEFINED',
      characterKnowledge: 'NOT_APPLICABLE',
      disclosureDefault: 'NOT_APPLICABLE',
      sourceSection: 'I4',
      closureNote: 'Production 전 closure 필요',
    }),
  ]),
}) satisfies CharacterFactAuthorityRegistryV1;
