import type {
  ProductionRelationshipHistoryRecordV1,
  SeyeonEventAuthorityDecisionV1,
  SeyeonRelationshipEventV2,
} from '../../../packages/domain/src/index.js';
import type {
  ProductionRelationshipApplyCommitPortV1,
  ProductionRelationshipApplyContextPortV1,
} from './production-relationship-event-apply-command-v1.js';
import {
  readSeyeonProductionRelationshipTurnBindingV1,
  type SeyeonProductionRelationshipReadAuthorityPortV1,
  type SeyeonRelationshipBandProjectionV1,
  type SeyeonRelationshipBandProjectorV1,
  type SeyeonProductionRelationshipTurnBindingV1,
} from './seyeon-production-relationship-read-v1.js';
import {
  resolveSeyeonProductionRelationshipActivationV1,
  type SeyeonProductionRelationshipActivationV1,
} from './seyeon-production-relationship-activation-v1.js';
import {
  syncSeyeonProductionRelationshipEventV1,
  type SeyeonProductionRelationshipModeV1,
  type SeyeonProductionRelationshipSyncIdPortV1,
  type SyncSeyeonProductionRelationshipEventV1Input,
  type SyncSeyeonProductionRelationshipEventV1Result,
} from './seyeon-production-relationship-sync-v1.js';

export const SEYEON_PRODUCTION_VERTICAL_SLICE_VERSION_V1 =
  'seyeon-production-vertical-slice-v1' as const;

export interface SeyeonCommittedTurnRelationshipSignalV1 {
  readonly committedTurn: Readonly<{
    readonly turnId: string;
    readonly assistantMessageRef: string;
    readonly occurredAt: string;
  }>;
  readonly relationshipEvent:
    | null
    | Readonly<{
        readonly experimentalEvent: SeyeonRelationshipEventV2;
        readonly authorityDecision: SeyeonEventAuthorityDecisionV1;
        readonly activeExperimentalEvents: readonly SeyeonRelationshipEventV2[];
      }>;
}

export interface RunSeyeonProductionVerticalSliceInputV1<TTurnResult> {
  readonly mode: SeyeonProductionRelationshipModeV1;
  readonly resolvedSubjectId: string;
  readonly bandProjection?: SeyeonRelationshipBandProjectionV1 | null;
  readonly bandProjector?: SeyeonRelationshipBandProjectorV1;
  readonly relationshipReadPort: SeyeonProductionRelationshipReadAuthorityPortV1;
  readonly productionHistoryRecords: readonly ProductionRelationshipHistoryRecordV1[];
  readonly productionAuthorityRef: string;
  readonly idPort: SeyeonProductionRelationshipSyncIdPortV1;
  readonly contextPort: ProductionRelationshipApplyContextPortV1;
  readonly commitPort: ProductionRelationshipApplyCommitPortV1;
  readonly durableSync?: SyncSeyeonProductionRelationshipEventV1Input['durableSync'];
  readonly runCommittedTurn: (input: Readonly<{
    readonly turnBinding: SeyeonProductionRelationshipTurnBindingV1;
    readonly activation: SeyeonProductionRelationshipActivationV1;
  }>) => Promise<
    Readonly<{
      readonly turnResult: TTurnResult;
      readonly signal: SeyeonCommittedTurnRelationshipSignalV1;
    }>
  >;
}

export interface RunSeyeonProductionVerticalSliceResultV1<TTurnResult> {
  readonly version: typeof SEYEON_PRODUCTION_VERTICAL_SLICE_VERSION_V1;
  readonly mode: SeyeonProductionRelationshipModeV1;
  readonly relationshipRevisionUsedForTurn: number | null;
  readonly relationshipRevisionAfterSync: number | null;
  readonly turnBinding: SeyeonProductionRelationshipTurnBindingV1;
  readonly activation: SeyeonProductionRelationshipActivationV1;
  readonly turnResult: TTurnResult;
  readonly syncResult: SyncSeyeonProductionRelationshipEventV1Result | null;
}

export class SeyeonProductionVerticalSliceErrorV1 extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'SeyeonProductionVerticalSliceErrorV1';
  }
}

function expectedRevision(
  binding: SeyeonProductionRelationshipTurnBindingV1,
): number {
  return binding.relationshipRevisionUsedForTurn ?? 0;
}

export async function runSeyeonProductionVerticalSliceV1<TTurnResult>(
  input: RunSeyeonProductionVerticalSliceInputV1<TTurnResult>,
): Promise<RunSeyeonProductionVerticalSliceResultV1<TTurnResult>> {
  const turnBinding = await readSeyeonProductionRelationshipTurnBindingV1({
    resolvedSubjectId: input.resolvedSubjectId,
    ...(input.bandProjection === undefined
      ? {}
      : { bandProjection: input.bandProjection }),
    ...(input.bandProjector === undefined
      ? {}
      : { bandProjector: input.bandProjector }),
    authorityPort: input.relationshipReadPort,
  });
  const activation = resolveSeyeonProductionRelationshipActivationV1({
    mode: input.mode,
    turnBinding,
  });

  // The committed turn callback receives one immutable pre-turn binding. No
  // relationship Event generated by this turn can alter that already-used input.
  const committed = await input.runCommittedTurn({
    turnBinding,
    activation,
  });

  const signal = committed.signal.relationshipEvent;
  if (signal === null || !activation.admissionEnabled) {
    return Object.freeze({
      version: SEYEON_PRODUCTION_VERTICAL_SLICE_VERSION_V1,
      mode: input.mode,
      relationshipRevisionUsedForTurn:
        turnBinding.relationshipRevisionUsedForTurn,
      relationshipRevisionAfterSync:
        turnBinding.relationshipRevisionUsedForTurn,
      turnBinding,
      activation,
      turnResult: committed.turnResult,
      syncResult: null,
    });
  }

  const beforeRevision = expectedRevision(turnBinding);
  const syncResult = await syncSeyeonProductionRelationshipEventV1({
    mode: input.mode,
    resolvedSubjectId: input.resolvedSubjectId,
    expectedRevision: beforeRevision,
    experimentalEvent: signal.experimentalEvent,
    authorityDecision: signal.authorityDecision,
    activeExperimentalEvents: signal.activeExperimentalEvents,
    productionHistoryRecords: input.productionHistoryRecords,
    committedTurn: committed.signal.committedTurn,
    productionAuthorityRef: input.productionAuthorityRef,
    idPort: input.idPort,
    contextPort: input.contextPort,
    commitPort: input.commitPort,
    ...(input.durableSync === undefined
      ? {}
      : { durableSync: input.durableSync }),
  });

  const afterRevision =
    syncResult.status === 'committed'
      ? syncResult.applyResult.revisionAfter
      : syncResult.status === 'shadow'
        ? syncResult.revisionAfter
        : beforeRevision;

  if (afterRevision < beforeRevision) {
    throw new SeyeonProductionVerticalSliceErrorV1(
      'Post-turn relationship sync cannot move the physical revision backwards.',
    );
  }

  return Object.freeze({
    version: SEYEON_PRODUCTION_VERTICAL_SLICE_VERSION_V1,
    mode: input.mode,
    relationshipRevisionUsedForTurn:
      turnBinding.relationshipRevisionUsedForTurn,
    relationshipRevisionAfterSync: afterRevision,
    turnBinding,
    activation,
    turnResult: committed.turnResult,
    syncResult,
  });
}
