/**
 * Offline state-transition reference for a future PostgreSQL-backed Cost Governor.
 *
 * Not a Production admission port: caller-owned snapshots are not concurrency
 * safe. Production MUST use a single atomic database transaction for reserve.
 * No AI calls, entitlement charges, network access or persistence occur here.
 */
export const SEYEON_COST_GOVERNOR_CONTRACT_VERSION_V1 =
  'seyeon-cost-governor-contract-v1' as const;

export type SeyeonCostStageV1 =
  | 'integrity_classification'
  | 'disclosure_classification'
  | 'unified_preflight_shadow'
  | 'turn_interpretation'
  | 'turn_interpret_render_shadow'
  | 'dialogue_render'
  | 'semantic_review'
  | 'event_extraction';

export type SeyeonCostReservationStateV1 =
  | 'RESERVED'
  | 'DISPATCHED'
  | 'HELD_UNKNOWN_USAGE'
  | 'SETTLED'
  | 'OVER_CEILING'
  | 'RELEASED_UNSENT';

export interface SeyeonCostReservationIdentityV1 {
  /** Generated by the server: unique per model call, not merely per chat turn. */
  readonly reservationKey: string;
  readonly bucketUtcDate: string;
  readonly subjectId: string;
  readonly turnId: string;
  readonly attemptId: string;
  readonly stage: SeyeonCostStageV1;
  readonly modelKey: string;
  readonly rateCardVersion: string;
  /** Quote from separately enforced model request token caps. */
  readonly ceilingMicroUsd: number;
}

export interface SeyeonCostReservationV1 extends SeyeonCostReservationIdentityV1 {
  readonly state: SeyeonCostReservationStateV1;
  readonly actualEstimatedMicroUsd: number | null;
  readonly reconciliationEvidenceId: string | null;
}

export interface SeyeonCostGovernorSnapshotV1 {
  readonly version: typeof SEYEON_COST_GOVERNOR_CONTRACT_VERSION_V1;
  readonly reservations: readonly SeyeonCostReservationV1[];
}

export interface SeyeonCostBudgetPolicyV1 {
  readonly bucketUtcDate: string;
  readonly globalLimitMicroUsd: number;
  readonly subjectLimitMicroUsd: number;
}

export type SeyeonCostAdmissionDispositionV1 =
  | 'ADMITTED'
  | 'DENIED_GLOBAL'
  | 'DENIED_SUBJECT'
  | 'DUPLICATE';

export interface SeyeonCostAdmissionResultV1 {
  readonly disposition: SeyeonCostAdmissionDispositionV1;
  readonly snapshot: SeyeonCostGovernorSnapshotV1;
  readonly reservation: SeyeonCostReservationV1 | null;
}

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/u;
const DATE_RE = /^\d{4}-\d{2}-\d{2}$/u;
const STAGES = new Set<SeyeonCostStageV1>([
  'integrity_classification', 'disclosure_classification',
  'unified_preflight_shadow', 'turn_interpretation',
  'turn_interpret_render_shadow', 'dialogue_render',
  'semantic_review', 'event_extraction',
]);

function validateUuid(value: string, name: string): void {
  if (!UUID_RE.test(value)) throw new TypeError('Invalid Cost Governor ' + name + '.');
}
function validateText(value: string, name: string, maxLength = 256): void {
  if (typeof value !== 'string' || value.trim() !== value ||
      value.length < 1 || value.length > maxLength) {
    throw new TypeError('Invalid Cost Governor ' + name + '.');
  }
}
function validateAmount(value: number, name: string, allowZero = false): void {
  if (!Number.isSafeInteger(value) || value < (allowZero ? 0 : 1)) {
    throw new TypeError('Invalid Cost Governor ' + name + ' microUSD.');
  }
}
function validateDate(value: string): void {
  if (typeof value !== 'string' || !DATE_RE.test(value) ||
      new Date(value + 'T00:00:00Z').toISOString().slice(0, 10) !== value) {
    throw new TypeError('Invalid Cost Governor UTC budget bucket.');
  }
}
function validateIdentity(input: SeyeonCostReservationIdentityV1): void {
  validateText(input.reservationKey, 'reservation key', 512);
  validateDate(input.bucketUtcDate);
  validateUuid(input.subjectId, 'Subject');
  validateUuid(input.turnId, 'turn');
  validateUuid(input.attemptId, 'attempt');
  if (!STAGES.has(input.stage)) throw new TypeError('Invalid Cost Governor stage.');
  validateText(input.modelKey, 'model key');
  validateText(input.rateCardVersion, 'rate card version');
  validateAmount(input.ceilingMicroUsd, 'reservation ceiling', true);
}
function validatePolicy(policy: SeyeonCostBudgetPolicyV1): void {
  validateDate(policy.bucketUtcDate);
  validateAmount(policy.globalLimitMicroUsd, 'global budget');
  validateAmount(policy.subjectLimitMicroUsd, 'Subject budget');
}
function makeSnapshot(
  reservations: readonly SeyeonCostReservationV1[],
): SeyeonCostGovernorSnapshotV1 {
  return Object.freeze({
    version: SEYEON_COST_GOVERNOR_CONTRACT_VERSION_V1,
    reservations: Object.freeze([...reservations]),
  });
}

export function emptySeyeonCostGovernorSnapshotV1(): SeyeonCostGovernorSnapshotV1 {
  return makeSnapshot([]);
}

function occupyingAmount(reservation: SeyeonCostReservationV1): bigint {
  switch (reservation.state) {
    case 'RELEASED_UNSENT': return 0n;
    case 'SETTLED':
    case 'OVER_CEILING':
      if (reservation.actualEstimatedMicroUsd === null) {
        throw new TypeError('Settled reservation cannot have missing usage.');
      }
      return BigInt(reservation.actualEstimatedMicroUsd);
    default: return BigInt(reservation.ceilingMicroUsd);
  }
}
function occupiedMicroUsd(
  snapshot: SeyeonCostGovernorSnapshotV1,
  utcDate: string,
  subjectId: string | null,
): bigint {
  return snapshot.reservations.reduce((sum, r) =>
    r.bucketUtcDate !== utcDate || (subjectId !== null && r.subjectId !== subjectId)
      ? sum : sum + occupyingAmount(r), 0n);
}
function sameIdentity(
  a: SeyeonCostReservationIdentityV1,
  b: SeyeonCostReservationIdentityV1,
): boolean {
  return a.reservationKey === b.reservationKey &&
    a.bucketUtcDate === b.bucketUtcDate &&
    a.subjectId === b.subjectId &&
    a.turnId === b.turnId &&
    a.attemptId === b.attemptId &&
    a.stage === b.stage &&
    a.modelKey === b.modelKey &&
    a.rateCardVersion === b.rateCardVersion &&
    a.ceilingMicroUsd === b.ceilingMicroUsd;
}

/** Reference logic. A real admission must be atomic across all Subjects. */
export function reserveSeyeonCostCandidateV1(input: {
  readonly snapshot: SeyeonCostGovernorSnapshotV1;
  readonly identity: SeyeonCostReservationIdentityV1;
  readonly policy: SeyeonCostBudgetPolicyV1;
}): SeyeonCostAdmissionResultV1 {
  validateIdentity(input.identity);
  validatePolicy(input.policy);
  if (input.identity.bucketUtcDate !== input.policy.bucketUtcDate) {
    throw new TypeError('Cost Governor reservation does not match the server budget bucket.');
  }
  const prior = input.snapshot.reservations.find(
    r => r.reservationKey === input.identity.reservationKey,
  );
  if (prior !== undefined) {
    if (!sameIdentity(prior, input.identity)) {
      throw new TypeError('Cost Governor reservation key conflicts with another request.');
    }
    // Even if settled/released, a duplicated request MUST NOT call the AI again.
    return Object.freeze({ disposition: 'DUPLICATE', snapshot: input.snapshot, reservation: prior });
  }
  const required = BigInt(input.identity.ceilingMicroUsd);
  const global = occupiedMicroUsd(input.snapshot, input.policy.bucketUtcDate, null);
  if (global + required > BigInt(input.policy.globalLimitMicroUsd)) {
    return Object.freeze({ disposition: 'DENIED_GLOBAL', snapshot: input.snapshot, reservation: null });
  }
  const subject = occupiedMicroUsd(
    input.snapshot, input.policy.bucketUtcDate, input.identity.subjectId,
  );
  if (subject + required > BigInt(input.policy.subjectLimitMicroUsd)) {
    return Object.freeze({ disposition: 'DENIED_SUBJECT', snapshot: input.snapshot, reservation: null });
  }
  const reservation = Object.freeze({
    ...input.identity,
    state: 'RESERVED' as const,
    actualEstimatedMicroUsd: null,
    reconciliationEvidenceId: null,
  });
  return Object.freeze({
    disposition: 'ADMITTED',
    snapshot: makeSnapshot([...input.snapshot.reservations, reservation]),
    reservation,
  });
}

function changeReservation(
  snapshot: SeyeonCostGovernorSnapshotV1,
  key: string,
  change: (record: SeyeonCostReservationV1) => SeyeonCostReservationV1,
): SeyeonCostGovernorSnapshotV1 {
  let found = false;
  const result = snapshot.reservations.map(record => {
    if (record.reservationKey !== key) return record;
    if (found) throw new TypeError('Duplicate Cost Governor reservation key in snapshot.');
    found = true;
    return Object.freeze(change(record));
  });
  if (!found) throw new TypeError('Cost Governor reservation does not exist.');
  return makeSnapshot(result);
}

/**
 * Mark dispatch BEFORE handing off to the provider. A replayed dispatch throws:
 * caller must not issue the same model request twice.
 */
export function markSeyeonCostDispatchedV1(
  snapshot: SeyeonCostGovernorSnapshotV1,
  reservationKey: string,
): SeyeonCostGovernorSnapshotV1 {
  return changeReservation(snapshot, reservationKey, record => {
    if (record.state !== 'RESERVED') {
      throw new TypeError('Cost Governor model dispatch must not be replayed.');
    }
    return { ...record, state: 'DISPATCHED' };
  });
}

/** Only proven NOT-SENT calls can release their reservation. */
export function releaseUnsentSeyeonCostReservationV1(
  snapshot: SeyeonCostGovernorSnapshotV1,
  reservationKey: string,
): SeyeonCostGovernorSnapshotV1 {
  return changeReservation(snapshot, reservationKey, record => {
    if (record.state !== 'RESERVED') {
      throw new TypeError('Cannot release a dispatched or already-resolved model request.');
    }
    return { ...record, state: 'RELEASED_UNSENT' };
  });
}

/** Unknown provider usage may still be billed; retain the reserved amount. */
export function holdUnknownSeyeonCostUsageV1(
  snapshot: SeyeonCostGovernorSnapshotV1,
  reservationKey: string,
): SeyeonCostGovernorSnapshotV1 {
  return changeReservation(snapshot, reservationKey, record => {
    if (record.state !== 'DISPATCHED') {
      throw new TypeError('Only dispatched model requests can be held for unknown usage.');
    }
    return { ...record, state: 'HELD_UNKNOWN_USAGE' };
  });
}

/** Provider usage must be validated by the accounting contract before settlement. */
export function settleSeyeonCostReservationV1(
  snapshot: SeyeonCostGovernorSnapshotV1,
  reservationKey: string,
  actualEstimatedMicroUsd: number,
): SeyeonCostGovernorSnapshotV1 {
  validateAmount(actualEstimatedMicroUsd, 'actual estimate', true);
  return changeReservation(snapshot, reservationKey, record => {
    if (record.state === 'SETTLED' || record.state === 'OVER_CEILING') {
      if (record.actualEstimatedMicroUsd !== actualEstimatedMicroUsd) {
        throw new TypeError('Conflicting Cost Governor settlement replay.');
      }
      return record;
    }
    if (record.state !== 'DISPATCHED') {
      throw new TypeError('Cost Governor cannot settle a request that was not dispatched.');
    }
    return {
      ...record,
      state: actualEstimatedMicroUsd > record.ceilingMicroUsd
        ? 'OVER_CEILING' : 'SETTLED',
      actualEstimatedMicroUsd,
    };
  });
}

/**
 * A held unknown-usage call can only be reconciled with an auditable evidence
 * reference and a validated cost. There is no automatic timeout refund.
 */
export function reconcileHeldSeyeonCostReservationV1(
  snapshot: SeyeonCostGovernorSnapshotV1,
  reservationKey: string,
  input: { readonly evidenceId: string; readonly verifiedActualEstimatedMicroUsd: number },
): SeyeonCostGovernorSnapshotV1 {
  validateText(input.evidenceId, 'reconciliation evidence');
  validateAmount(input.verifiedActualEstimatedMicroUsd, 'reconciled estimate', true);
  return changeReservation(snapshot, reservationKey, record => {
    if (record.state === 'SETTLED' || record.state === 'OVER_CEILING') {
      if (record.reconciliationEvidenceId !== input.evidenceId ||
          record.actualEstimatedMicroUsd !== input.verifiedActualEstimatedMicroUsd) {
        throw new TypeError('Conflicting Cost Governor reconciliation replay.');
      }
      return record;
    }
    if (record.state !== 'HELD_UNKNOWN_USAGE') {
      throw new TypeError('Only held requests can be reconciled.');
    }
    return {
      ...record,
      state: input.verifiedActualEstimatedMicroUsd > record.ceilingMicroUsd
        ? 'OVER_CEILING' : 'SETTLED',
      actualEstimatedMicroUsd: input.verifiedActualEstimatedMicroUsd,
      reconciliationEvidenceId: input.evidenceId,
    };
  });
}

export function inspectSeyeonCostBudgetV1(
  snapshot: SeyeonCostGovernorSnapshotV1,
  input: { readonly bucketUtcDate: string; readonly subjectId: string },
): Readonly<{ globalOccupiedMicroUsd: number; subjectOccupiedMicroUsd: number }> {
  validateDate(input.bucketUtcDate);
  validateUuid(input.subjectId, 'Subject');
  const global = occupiedMicroUsd(snapshot, input.bucketUtcDate, null);
  const subject = occupiedMicroUsd(snapshot, input.bucketUtcDate, input.subjectId);
  if (global > BigInt(Number.MAX_SAFE_INTEGER) ||
      subject > BigInt(Number.MAX_SAFE_INTEGER)) {
    throw new RangeError('Cost Governor aggregate overflow.');
  }
  return Object.freeze({
    globalOccupiedMicroUsd: Number(global),
    subjectOccupiedMicroUsd: Number(subject),
  });
}
