\set ON_ERROR_STOP on

DO $$
DECLARE
  v_role text;
  v_count integer;
BEGIN
  FOR v_role IN SELECT unnest(ARRAY['anon', 'authenticated'])
  LOOP
    SELECT count(*)
      INTO v_count
    FROM pg_catalog.pg_class c
    JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public'
      AND c.relkind IN ('r', 'p', 'v', 'm', 'f')
      AND (
        pg_catalog.has_table_privilege(v_role, c.oid, 'SELECT')
        OR pg_catalog.has_table_privilege(v_role, c.oid, 'INSERT')
        OR pg_catalog.has_table_privilege(v_role, c.oid, 'UPDATE')
        OR pg_catalog.has_table_privilege(v_role, c.oid, 'DELETE')
        OR pg_catalog.has_table_privilege(v_role, c.oid, 'TRUNCATE')
        OR pg_catalog.has_table_privilege(v_role, c.oid, 'REFERENCES')
        OR pg_catalog.has_table_privilege(v_role, c.oid, 'TRIGGER')
      );

    IF v_count <> 0 THEN
      RAISE EXCEPTION 'FAIL % retains privileges on % public table-like objects', v_role, v_count;
    END IF;

    SELECT count(*)
      INTO v_count
    FROM pg_catalog.pg_class c
    JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public'
      AND c.relkind = 'S'
      AND (
        pg_catalog.has_sequence_privilege(v_role, c.oid, 'USAGE')
        OR pg_catalog.has_sequence_privilege(v_role, c.oid, 'SELECT')
        OR pg_catalog.has_sequence_privilege(v_role, c.oid, 'UPDATE')
      );

    IF v_count <> 0 THEN
      RAISE EXCEPTION 'FAIL % retains privileges on % public sequences', v_role, v_count;
    END IF;

    SELECT count(*)
      INTO v_count
    FROM pg_catalog.pg_proc p
    JOIN pg_catalog.pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'public'
      AND pg_catalog.has_function_privilege(v_role, p.oid, 'EXECUTE');

    IF v_count <> 0 THEN
      RAISE EXCEPTION 'FAIL % retains EXECUTE on % public functions', v_role, v_count;
    END IF;

    IF pg_catalog.has_schema_privilege(v_role, 'public', 'CREATE') THEN
      RAISE EXCEPTION 'FAIL % retains CREATE on public schema', v_role;
    END IF;
  END LOOP;

  IF NOT pg_catalog.has_function_privilege(
    'myeongha_api_executor',
    'public.qry_guest_bootstrap_current_v1(uuid)'::pg_catalog.regprocedure,
    'EXECUTE'
  ) THEN
    RAISE EXCEPTION 'FAIL myeongha_api_executor lost guest bootstrap EXECUTE';
  END IF;

  IF NOT pg_catalog.has_function_privilege(
    'myeongha_api_executor',
    'public.cmd_promote_guest_runtime_v1(uuid,uuid,uuid)'::pg_catalog.regprocedure,
    'EXECUTE'
  ) THEN
    RAISE EXCEPTION 'FAIL myeongha_api_executor lost guest promotion EXECUTE';
  END IF;
END
$$;

BEGIN;

CREATE TABLE public.__acl_future_table (
  id bigint generated by default as identity primary key,
  payload text
);

CREATE SEQUENCE public.__acl_future_sequence;

CREATE FUNCTION public.__acl_future_function()
RETURNS integer
LANGUAGE sql
AS $$ SELECT 1 $$;

DO $$
DECLARE
  v_role text;
BEGIN
  FOR v_role IN SELECT unnest(ARRAY['anon', 'authenticated'])
  LOOP
    IF pg_catalog.has_table_privilege(v_role, 'public.__acl_future_table', 'SELECT')
       OR pg_catalog.has_table_privilege(v_role, 'public.__acl_future_table', 'INSERT')
       OR pg_catalog.has_table_privilege(v_role, 'public.__acl_future_table', 'UPDATE')
       OR pg_catalog.has_table_privilege(v_role, 'public.__acl_future_table', 'DELETE')
       OR pg_catalog.has_table_privilege(v_role, 'public.__acl_future_table', 'TRUNCATE')
       OR pg_catalog.has_table_privilege(v_role, 'public.__acl_future_table', 'REFERENCES')
       OR pg_catalog.has_table_privilege(v_role, 'public.__acl_future_table', 'TRIGGER') THEN
      RAISE EXCEPTION 'FAIL future table default ACL reopened for %', v_role;
    END IF;

    IF pg_catalog.has_sequence_privilege(v_role, 'public.__acl_future_sequence', 'USAGE')
       OR pg_catalog.has_sequence_privilege(v_role, 'public.__acl_future_sequence', 'SELECT')
       OR pg_catalog.has_sequence_privilege(v_role, 'public.__acl_future_sequence', 'UPDATE') THEN
      RAISE EXCEPTION 'FAIL future sequence default ACL reopened for %', v_role;
    END IF;

    IF pg_catalog.has_function_privilege(
      v_role,
      'public.__acl_future_function()'::pg_catalog.regprocedure,
      'EXECUTE'
    ) THEN
      RAISE EXCEPTION 'FAIL future function default ACL reopened for %', v_role;
    END IF;
  END LOOP;
END
$$;

ROLLBACK;

SELECT 'api_role_acl_negative: PASS' AS result;